# Build settings
markdown: kramdown
#theme: jekyll-theme-blackdoc
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postfiles
  - jekyll-category-pages

# DEV SERVER INFO
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
host:    0.0.0.0
port:    4000
baseurl: "" # does not include hostname
source:      .
destination: ./_site

### SERVER SETUP
url: "westonganger.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/toyota_22re_tech/" # the subpath of your site, e.g. /blog/
timezone: "Pacific Time (US & Canada)"

### SITE SETTINGS
title: Toyota 22RE Tech
tagline: A collection of guides and information for 1986-1995 Toyota 4runner & Pickup Trucks
description: >- # this means to ignore newlines until "baseurl:"
  A automotive tech information site for Toyota 22RE 4Runner / Pickup.
email: westonganger@gmail.com
github_username:  westonganger

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Weston Ganger"

### FOR SITEMAP PLUGIN IN _plugins/sitemap.rb
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

### FOR CATEGORY PAGES PLUGIN
category_path: "/category"
category_layout: "category_index.html"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
