deploy:
  - rsync -aze ssh --delete ./ weston@westonganger.com:/usr/share/nginx/html/jekyll-template  

# Build settings
markdown: kramdown
#theme: jekyll-theme-blackdoc
plugins:
  - jekyll-slim
  - jekyll-assets
  - jekyll-manager
  - jekyll-archives
  #- jekyll-polyglot # translations
  - jekyll-paginate-v2
  - jekyll-postfiles
  - jekyll-contentblocks
  - jekyll-picture-tag
  - jekyll-figure
  - jekyll_inline_highlight
  - liquid_pluralize
  - liquid-humanize-number-filter
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-liquify
  - jekyll-firstimage
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# DEV SERVER INFO
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
host:    0.0.0.0
port:    4000
baseurl: "" # does not include hostname
source:      .
destination: ./_site

### SERVER SETUP
url: "westonganger.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/toyota_22re_tech/" # the subpath of your site, e.g. /blog/
timezone: "Pacific Time (US & Canada)"

### SITE SETTINGS
title: Toyota 22RE Tech
tagline: A collection of guides and information for 1986-1995 Toyota 4runner & Pickup Trucks
description: >- # this means to ignore newlines until "baseurl:"
  A automotive tech information site for Toyota 22RE 4Runner / Pickup.
email: westonganger@gmail.com
github_username:  westonganger

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Weston Ganger"

### FOR SITEMAP PLUGIN IN _plugins/sitemap.rb
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

### FOR CATEGORY PAGES PLUGIN
category_path: "/category"
category_layout: "category_index.html"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

### Jekyll-Assets config: https://github.com/envygeeks/jekyll-assets
assets:
  gzip: true

### Jekyll-Polyglot config: https://github.com/untra/polyglot
### languages: ["en", "sv", "de", "fr"]
#default_lang: "en"
#exclude_from_localization: ["javascript", "images", "css", "_assets"]
#parallel_localization: true

### Jekyll-Paginate-V2: https://github.com/sverrirs/jekyll-paginate-v2
pagination:
  enabled: true
  debug: false # This can be enabled in the site config or only for individual pagination pages
  extension: html
  indexpage: 'index' # Optional, the default name of the index file for generated pages (e.g. 'index.html') Without file extension
  collection: 'posts' # default document collection to paginate if nothing is specified
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ':title - page :num' # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  limit: 0 # Limit how many pagenated pages to create (default: 0, means all)
  sort_field: 'date'
  sort_reverse: true
  tag: '' # Optional, the default tag to use, omit to disable
  locale: '' # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts)
  trail: 
    before: 2
    after: 2

jekyll-archives:
  enabled: ['categories', 'tags'] # ['year','month','day','categories','tags']
  layout: default-archive
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

optional_front_matter:
  enabled: true
  remove_originals: true # remove original non-front-matter files from output

titles_from_headings:
  enabled:     true
  strip_title: false # If your theme renders titles based on page.title, you can remove the title from the content by setting strip_title to prevent rendering it twice.
  collections: false
# defaults:
#   - scope:
#       path: some-path
#       layout: some_layout
#     values:
#       strip_title: true

### Jekyll-Sitemap config: https://github.com/jekyll/jekyll-sitemap
sitemap: true
# defaults:
#   scope:
#     path:            "assets/**/*.pdf"
#   values:
#     sitemap:         false
